# Generated by Django 5.1.3 on 2024-11-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coleta_Organica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep_inicio', models.CharField(help_text='CEP inicial da faixa atendida (ex: 74000-000)', max_length=9)),
                ('cep_fim', models.CharField(help_text='CEP final da faixa atendida (ex: 74999-999)', max_length=9)),
                ('dia_semana', models.CharField(help_text='Dia da semana em que a coleta ocorre, caso seja mais de um preencher com vírgula (ex: Segunda-feira, Quarta-feira, Sexta-feira)', max_length=84)),
                ('turno', models.CharField(help_text='Período do dia (Diurno ou Noturno, somente um dos dois)', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Coleta_Seletiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep_inicio', models.CharField(help_text='CEP inicial da faixa atendida (ex: 74000-000)', max_length=9)),
                ('cep_fim', models.CharField(help_text='CEP final da faixa atendida (ex: 74999-999)', max_length=9)),
                ('dia_semana', models.CharField(help_text='Dia da semana em que a coleta ocorre, caso seja mais de um preencher com vírgula (ex: Segunda-feira, Quarta-feira, Sexta-feira)', max_length=86)),
                ('turno', models.CharField(help_text='Período do dia (Diurno ou Noturno, somente um dos dois)', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Eco_pontos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(help_text='Nome do ecoponto (ex: Ecoponto do Setor Bueno)', max_length=50)),
                ('Dias_funcionamento', models.CharField(help_text='Dias de funcionamento do ecoponto (ex: Segunda-feira a Sexta-feira)', max_length=30)),
                ('Horario_funcionamento', models.CharField(help_text='Horário de funcionamento do ecoponto (ex: 08:00 às 18:00)', max_length=15)),
                ('endereco', models.CharField(help_text='Endereço do ecoponto', max_length=84)),
                ('cep', models.CharField(help_text='CEP do ecoponto (ex: 74000-000)', max_length=9)),
            ],
        ),
    ]
